
running 1 test
test tests::test_test_case ... ok
test tests::test_test_function ... ok

failures:

---- tests::test_failing stdout ----
Oh noes!!
thread 'tests::test_failing' panicked at 'assertion failed: false', src\main.rs:93:12
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71

---- tests::test_failing2 stdout ----
Again!!
thread 'tests::test_failing2' panicked at 'assertion failed: `(left == right)`
  left: `"no"`,
 right: `"yes"`', src\main.rs:100:9
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71


failures:
    tests::test_failing
    tests::test_failing2
    tests::test_test_failures

test result: ok. 1 passed; 2 failed; 3 ignored; 4 measured; 5 filtered out


running 1 test
test src/hexfile.rs - hexfile::MBHexFile::new (line 102) ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

